// This file was autogenerated by parse_grammar.lua from scala.ebnf.

/*
 * inline constants: 
 * blockStatementSeq        := _block_statement (_semicolon _block_statement)* _semicolon?
 * charEscapeSeq            := \\[btnfr"'\\]
 * charMinusQuoteDollar     := [^"\$]
 * charNoBQOrNL             := [\u0020-\u005f\u0061-\u007f]
 * classDef                 := (identifier: name) (type_parameters?: type_parameters) (constructor_annotation*: constructor_annotations)
 (access_modifier?: access_modifier)
 (class_parameters*: class_parameters)
 $classTemplateOpt

 *     ((identifier: name) (type_parameters?: type_parameters) (constructor_annotation*: constructor_annotations)
 (access_modifier?: access_modifier)
 (class_parameters*: class_parameters)
 ('extends' _class_template | ('extends'? template_body)?)
)
 * classTemplateOpt         := ('extends' _class_template | ('extends'? template_body)?)
 * decimal_numeral          := [0-9]+
 * escapeSeq                := ($unicodeEscape|$charEscapeSeq)
 *     ((\\u+[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]|\\[btnfr"'\\]))
 * exponentPart             := ([Ee][+-]?$decimal_numeral)
 *     (([Ee][+-]?[0-9]+))
 * floatType                := [FfDd]
 * floating_point_literal   := /-?($fp_lit_1|$fp_lit_2|$fp_lit_3|$fp_lit_4)/
 *     (/-?([0-9]+[.][0-9]+([Ee][+-]?[0-9]+)?[FfDd]?|[.][0-9]+([Ee][+-]?[0-9]+)?[FfDd]?|[0-9]+([Ee][+-]?[0-9]+)?[FfDd]|[0-9]+([Ee][+-]?[0-9]+)[FfDd]?)/)
 * fp_lit_1                 := $decimal_numeral[.]$decimal_numeral$exponentPart?$floatType?
 *     ([0-9]+[.][0-9]+([Ee][+-]?[0-9]+)?[FfDd]?)
 * fp_lit_2                 := [.]$decimal_numeral$exponentPart?$floatType?
 *     ([.][0-9]+([Ee][+-]?[0-9]+)?[FfDd]?)
 * fp_lit_3                 := $decimal_numeral$exponentPart?$floatType
 *     ([0-9]+([Ee][+-]?[0-9]+)?[FfDd])
 * fp_lit_4                 := $decimal_numeral$exponentPart$floatType?
 *     ([0-9]+([Ee][+-]?[0-9]+)[FfDd]?)
 * functionDcl              := (identifier: name) (type_parameters?: type_parameters) (parameters*: parameters) (':' (_type: return_type))?

 * functionDef              := (identifier: name) (type_parameters?: type_parameters) (parameters*: parameters) (':' (_type: return_type))?
 (('=' (_expression: body)) | (block: body))

 * hexDigit                 := [0-9a-fA-F]
 * hex_numeral              := 0[xX]$hexDigit+
 *     (0[xX][0-9a-fA-F]+)
 * idRegex                  := $plainid|[`]($charNoBQOrNL|$escapeSeq)*[`]
 *     (([\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$][\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]*(_[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)?|[\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F_][\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]*(_[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)?|[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)|[`]([\u0020-\u005f\u0061-\u007f]|(\\u+[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]|\\[btnfr"'\\]))*[`])
 * idrest                   := [$(letter)0-9]*(_$opchar+)?
 *     ([\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]*(_[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)?)
 * importPrefix             := (identifier '.')+
 * integer_literal          := /-?($decimal_numeral|$hex_numeral)[Ll]?/
 *     (/-?([0-9]+|0[xX][0-9a-fA-F]+)[Ll]?/)
 * letter                   := $upperChars$lowerChars
 *     (\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F)
 * localDefPrefix           := _annotations? ('implicit' -> implicit_modifier)? ('lazy' -> lazy_modifier)?
 * lowerChars               := $lowerChars1$lowerChars2$lowerChars3
 *     (\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F)
 * lowerChars1              := \p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4
 * lowerChars2              := \u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C
 * lowerChars3              := \u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F
 * objectDef                := (identifier: name) $classTemplateOpt
 *     ((identifier: name) ('extends' _class_template | ('extends'? template_body)?))
 * opchar                   := [\-!#%&*+/\\:<=>?@\u005e\u007c~]
 * packageDef               := ('package' package_identifier)
 * patternVarDefinition     := (_pattern: pattern) (':' (_type: type))? '=' (_expression: value)
 * plainid                  := ($upper$idrest|$varidRegex|$opchar+)
 *     (([\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$][\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]*(_[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)?|[\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F_][\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]*(_[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)?|[\-!#%&*+/\\:<=>?@\u005e\u007c~]+))
 * stableTypeIdentifer      := (_type_identifier | stable_identifier -> stable_type_identifier)
 * topLevelStatementSeq     := (_top_level_statement (_semicolon _top_level_statement)*)
 * traitDef                 := (identifier: name) (type_parameters?: type_parameters) $traitTemplateOpt
 *     ((identifier: name) (type_parameters?: type_parameters) ('extends' _trait_template | ('extends'? template_body)?))
 * traitTemplateOpt         := ('extends' _trait_template | ('extends'? template_body)?)
 * typeDcl                  := (_type_parameter: name) (type_parameters?: type_parameters) lower_bound? upper_bound?

 * typeDef                  := (_type_identifier: name) (type_parameters?: type_parameters) '=' (_type: type)

 * types                    := _type (',' _type)*
 * unicodeEscape            := \\u+$hexDigit$hexDigit$hexDigit$hexDigit
 *     (\\u+[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F])
 * upper                    := [$upperChars]
 *     ([\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$])
 * upperChars               := \p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$
 * valDcl                   := ((identifier: name) (',' (identifier: name))*) ':' (_type: type)
 * varDcl                   := ((identifier: name) (',' (identifier: name))*) ':' (_type: type)
 * varidRegex               := [$(lowerChars)_]$idrest
 *     ([\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F_][\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]*(_[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)?)
 */

module.exports = grammar({
  name: 'scala',

  /*
   * scala.ebnf:2
   * supertypes ::= { _expression _definition _pattern }
   */
  supertypes: $ => [$._expression, $._definition, $._pattern],
  /*
   * scala.ebnf:4-11
   * externals  ::= {
   *                _whitespace
   *                _newline
   *                comment
   *                _automatic_semicolon
   *                _block_newlines
   *                _empty
   *                }
   */
  externals: $ => [
                    $._whitespace,
                    $._newline,
                    $.comment,
                    $._automatic_semicolon,
                    $._block_newlines,
                    $._empty
                  ],
  /*
   * scala.ebnf:13
   * extras     ::= { [ \r\t] _whitespace comment }
   */
  extras: $ => [/[ \r\t]/, $._whitespace, $.comment],
  /*
   * scala.ebnf:15
   * inline     ::= { _pattern _semicolon _definition _type_identifier _param_type }
   */
  inline: $ => [$._pattern, $._semicolon, $._definition, $._type_identifier, $._param_type],
  /*
   * scala.ebnf:17
   * conflicts  ::= { }
   */
  conflicts: $ => [],
  /*
   * scala.ebnf:19
   * word       ::= identifier
   */
  word: $ => $.identifier,
  rules: {
    /*
     * scala.ebnf:22-23
     * compilation_unit             ::= ($packageDef _semicolon)* $packageDef? $topLevelStatementSeq?
     *                                | $blockStatementSeq
     */
    compilation_unit: $ => choice(
                             seq(
                               repeat(seq(seq('package', $.package_identifier), $._semicolon)),
                               optional(seq('package', $.package_identifier)),
                               optional(seq($._top_level_statement, repeat(seq($._semicolon, $._top_level_statement))))
                             ),
                             seq(
                               $._block_statement,
                               repeat(seq($._semicolon, $._block_statement)),
                               optional($._semicolon)
                             )
                           ),
    /*
     * scala.ebnf:25-31
     * _literal                     ::= number
     *                                | boolean_literal
     *                                | character_literal
     *                                | symbol_literal
     *                                | string_literal
     *                                | interpolated_string
     *                                | 'null'
     */
    _literal: $ => choice(
                     $.number,
                     $.boolean_literal,
                     $.character_literal,
                     $.symbol_literal,
                     $.string_literal,
                     $.interpolated_string,
                     'null'
                   ),
    /*
     * scala.ebnf:33-41
     * _top_level_statement         ::= 1(import
     *                                | _template_definition
     *                                | package_clause
     *                                | package_object)
     * ;TemplateStat         ::= Import
     *                        ;| (Annotation nl?)* Modifier* Def
     *                        ;| (Annotation nl?)* Modifier* Dcl
     *                        ;| Expr
     *                        ;| empty
     */
    _top_level_statement: $ => prec(1, choice($.import, $._template_definition, $.package_clause, $.package_object)),
    /*
     * scala.ebnf:42-55
     * _template_statement          ::= import
     *                                | val_definition
     *                                | var_definition
     *                                | function_definition
     *                                | type_definition
     *                                | _template_class_definition -> class_definition
     *                                | _template_object_definition -> object_definition
     *                                | _template_trait_definition -> trait_definition
     *                                | val_declaration
     *                                | var_declaration
     *                                | function_declaration
     *                                | type_declaration
     *                                | _expression
     *                                | _empty
     */
    _template_statement: $ => choice(
                                $.import,
                                $.val_definition,
                                $.var_definition,
                                $.function_definition,
                                $.type_definition,
                                alias($._template_class_definition, $.class_definition),
                                alias($._template_object_definition, $.object_definition),
                                alias($._template_trait_definition, $.trait_definition),
                                $.val_declaration,
                                $.var_declaration,
                                $.function_declaration,
                                $.type_declaration,
                                $._expression,
                                $._empty
                              ),
    /*
     * scala.ebnf:56-58
     * _template_definition         ::= _template_class_definition -> class_definition
     *                                | _template_object_definition -> object_definition
     *                                | _template_trait_definition -> trait_definition
     */
    _template_definition: $ => choice(
                                 alias($._template_class_definition, $.class_definition),
                                 alias($._template_object_definition, $.object_definition),
                                 alias($._template_trait_definition, $.trait_definition)
                               ),
    /*
     * scala.ebnf:59
     * _template_class_definition   ::= _annotations? modifiers? 'case'? 'class' $classDef
     */
    _template_class_definition: $ => seq(
                                       optional($._annotations),
                                       optional($.modifiers),
                                       optional('case'),
                                       'class',
                                       field('name', $.identifier),
                                       field('type_parameters', optional($.type_parameters)),
                                       field('constructor_annotations', repeat($.constructor_annotation)),
                                       field('access_modifier', optional($.access_modifier)),
                                       field('class_parameters', repeat($.class_parameters)),
                                       choice(
                                         seq('extends', $._class_template),
                                         optional(seq(optional('extends'), $.template_body))
                                       )
                                     ),
    /*
     * scala.ebnf:60
     * _template_object_definition  ::= _annotations? modifiers? 'case'? 'object' $objectDef
     */
    _template_object_definition: $ => seq(
                                        optional($._annotations),
                                        optional($.modifiers),
                                        optional('case'),
                                        'object',
                                        field('name', $.identifier),
                                        choice(
                                          seq('extends', $._class_template),
                                          optional(seq(optional('extends'), $.template_body))
                                        )
                                      ),
    /*
     * scala.ebnf:61
     * _template_trait_definition   ::= _annotations? modifiers? 'trait' $traitDef
     */
    _template_trait_definition: $ => seq(
                                       optional($._annotations),
                                       optional($.modifiers),
                                       'trait',
                                       field('name', $.identifier),
                                       field('type_parameters', optional($.type_parameters)),
                                       choice(
                                         seq('extends', $._trait_template),
                                         optional(seq(optional('extends'), $.template_body))
                                       )
                                     ),
    /*
     * scala.ebnf:71
     * _constructor                 ::= _annotated_type arguments*
     */
    _constructor: $ => seq($._annotated_type, repeat($.arguments)),
    /*
     * scala.ebnf:72
     * _class_template              ::= early_definitions? parent_classes template_body?
     */
    _class_template: $ => seq(optional($.early_definitions), $.parent_classes, optional($.template_body)),
    /*
     * scala.ebnf:73
     * _trait_template              ::= early_definitions? trait_parent_classes template_body?
     */
    _trait_template: $ => seq(optional($.early_definitions), $.trait_parent_classes, optional($.template_body)),
    /*
     * scala.ebnf:74
     * parent_classes               ::= _constructor: base_class ('with' _annotated_type: inherited_trait_name)*
     */
    parent_classes: $ => seq(
                           field('base_class', $._constructor),
                           repeat(seq('with', field('inherited_trait_name', $._annotated_type)))
                         ),
    /*
     * scala.ebnf:75
     * trait_parent_classes         ::= _annotated_type ('with' _annotated_type)*
     */
    trait_parent_classes: $ => seq($._annotated_type, repeat(seq('with', $._annotated_type))),
    /*
     * scala.ebnf:76
     * early_definitions            ::= ('{' (early_definition (_semicolon early_definition)*)? '}' 'with')
     */
    early_definitions: $ => seq(
                              '{',
                              optional(seq($.early_definition, repeat(seq($._semicolon, $.early_definition)))),
                              '}',
                              'with'
                            ),
    /*
     * scala.ebnf:77
     * early_definition             ::= 1(val_definition)
     */
    early_definition: $ => prec(1, $.val_definition),
    /*
     * scala.ebnf:78
     * template_body                ::= _block_newlines? '{' self_type? _template_statement (_semicolon _template_statement)* '}'
     */
    template_body: $ => seq(
                          optional($._block_newlines),
                          '{',
                          optional($.self_type),
                          $._template_statement,
                          repeat(seq($._semicolon, $._template_statement)),
                          '}'
                        ),
    /*
     * scala.ebnf:79
     * self_type                    ::= (identifier (':' type)? '=>' | 'this' ':' type '=>')
     */
    self_type: $ => choice(
                      seq($.identifier, optional(seq(':', $._type)), '=>'),
                      seq('this', ':', $._type, '=>')
                    ),
    /*
     * scala.ebnf:81-87
     * _block_statement             ::= import
     *                                | _local_val_definition -> val_definition
     *                                | _local_var_definition -> var_definition
     *                                | _local_function_definition -> function_definition
     *                                | _local_type_definition -> type_definition
     *                                | _template_definition
     *                                | _expression
     */
    _block_statement: $ => choice(
                             $.import,
                             alias($._local_val_definition, $.val_definition),
                             alias($._local_var_definition, $.var_definition),
                             alias($._local_function_definition, $.function_definition),
                             alias($._local_type_definition, $.type_definition),
                             $._template_definition,
                             $._expression
                           ),
    /*
     * scala.ebnf:88
     * import                       ::= 'import' _import_expr (',' _import_expr)*
     */
    import: $ => seq('import', $._import_expr, repeat(seq(',', $._import_expr))),
    /*
     * scala.ebnf:90
     * _import_stable_identifier ::= $importPrefix identifier
     */
    _import_stable_identifier: $ => seq(repeat1(seq($.identifier, '.')), $.identifier),
    /*
     * scala.ebnf:91-92
     * _import_expr                   ::= _import_stable_identifier -> stable_identifier
     *     | $importPrefix -> stable_identifier ('_' -> wildcard | import_selectors)
     */
    _import_expr: $ => choice(
                         alias($._import_stable_identifier, $.stable_identifier),
                         seq(
                           alias(repeat1(seq($.identifier, '.')), $.stable_identifier),
                           choice(alias('_', $.wildcard), $.import_selectors)
                         )
                       ),
    /*
     * scala.ebnf:93
     * import_selectors              ::= '{' (_import_selector ',')* (_import_selector | '_' -> wildcard) '}'
     */
    import_selectors: $ => seq(
                             '{',
                             repeat(seq($._import_selector, ',')),
                             choice($._import_selector, alias('_', $.wildcard)),
                             '}'
                           ),
    /*
     * scala.ebnf:94-106
     * _import_selector               ::= identifier ('=>' identifier | '=>' '_' -> wildcard)?
     * ;BlockStat            ::= Import
     *                        ;| Annotation* 'implicit'? 'lazy'? Def
     *                        ;| Annotation* LocalModifier* TmplDef
     *                        ;| Expr1
     *                        ;| empty
     * ;PatVarDef            ::= 'val' PatDef
     *                        ;| 'var' VarDef
     * ;Def                  ::= 1(PatVarDef
     *                        ;| 'def' FunDef
     *                        ;| 'type' nl* TypeDef
     *                        ;| TmplDef)
     * ;PatDef               ::= Pattern2 (':' Type)? '=' Expr
     */
    _import_selector: $ => seq(
                             $.identifier,
                             optional(choice(seq('=>', $.identifier), seq('=>', alias('_', $.wildcard))))
                           ),
    /*
     * scala.ebnf:108
     * package_identifier           ::= identifier ("." identifier)*
     */
    package_identifier: $ => seq($.identifier, repeat(seq(".", $.identifier))),
    /*
     * scala.ebnf:109-121
     * _definition                  ::= package_clause
     *                                | package_object
     *                                | class_definition
     *                                | import
     *                                | object_definition
     *                                | trait_definition
     *                                | val_definition
     *                                | val_declaration
     *                                | var_definition
     *                                | var_declaration
     *                                | type_definition
     *                                | function_definition
     *                                | function_declaration
     */
    _definition: $ => choice(
                        $.package_clause,
                        $.package_object,
                        $.class_definition,
                        $.import,
                        $.object_definition,
                        $.trait_definition,
                        $.val_definition,
                        $.val_declaration,
                        $.var_definition,
                        $.var_declaration,
                        $.type_definition,
                        $.function_definition,
                        $.function_declaration
                      ),
    /*
     * scala.ebnf:122
     * package_clause               ::= 'package' (package_identifier: name) '{' ($topLevelStatementSeq?: body) '}'
     */
    package_clause: $ => seq(
                           'package',
                           field('name', $.package_identifier),
                           '{',
                           field(
                             'body',
                             optional(seq($._top_level_statement, repeat(seq($._semicolon, $._top_level_statement))))
                           ),
                           '}'
                         ),
    /*
     * scala.ebnf:123
     * package_object               ::= 'package' 'object' _object_definition
     */
    package_object: $ => seq('package', 'object', $._object_definition),
    /*
     * scala.ebnf:124
     * renamed_identifier           ::= (identifier: name) '=>' ((identifier | wildcard): alias)
     */
    renamed_identifier: $ => seq(
                               field('name', $.identifier),
                               '=>',
                               field('alias', choice($.identifier, $.wildcard))
                             ),
    /*
     * scala.ebnf:125
     * object_definition            ::= _annotations? modifiers? 'case'? 'object' _object_definition
     */
    object_definition: $ => seq(
                              optional($._annotations),
                              optional($.modifiers),
                              optional('case'),
                              'object',
                              $._object_definition
                            ),
    /*
     * scala.ebnf:126
     * _object_definition           ::= (identifier: name) (extends_clause?: extend) (template_body?: body)
     */
    _object_definition: $ => seq(
                               field('name', $.identifier),
                               field('extend', optional($.extends_clause)),
                               field('body', optional($.template_body))
                             ),
    /*
     * scala.ebnf:127-129
     * class_definition             ::= _annotations? modifiers? 'case'? 'class' (identifier: name)
     *                                    (type_parameters?: type_parameters) (class_parameters*: class_parameters)
     *                                    (extends_clause?: extend) (template_body?: body)
     */
    class_definition: $ => seq(
                             optional($._annotations),
                             optional($.modifiers),
                             optional('case'),
                             'class',
                             field('name', $.identifier),
                             field('type_parameters', optional($.type_parameters)),
                             field('class_parameters', repeat($.class_parameters)),
                             field('extend', optional($.extends_clause)),
                             field('body', optional($.template_body))
                           ),
    /*
     * scala.ebnf:130-131
     * trait_definition             ::= 'trait' (identifier: name) (type_parameters?: type_parameters)
     *                                    (extends_clause?: extend) (template_body?: body)
     */
    trait_definition: $ => seq(
                             'trait',
                             field('name', $.identifier),
                             field('type_parameters', optional($.type_parameters)),
                             field('extend', optional($.extends_clause)),
                             field('body', optional($.template_body))
                           ),
    /*
     * scala.ebnf:132
     * _annotations                 ::= 2((annotation )+)
     */
    _annotations: $ => prec(2, repeat1($.annotation)),
    /*
     * scala.ebnf:133
     * annotation                   ::= >('@' (_simple_type: name) (arguments*: arguments))
     */
    annotation: $ => prec.right(seq('@', field('name', $._simple_type), field('arguments', repeat($.arguments)))),
    /*
     * scala.ebnf:134
     * constructor_annotation       ::= '@' (_simple_type: name) (arguments: arguments)
     */
    constructor_annotation: $ => seq('@', field('name', $._simple_type), field('arguments', $.arguments)),
    /*
     * scala.ebnf:151
     * _local_val_definition        ::= 1($localDefPrefix 'val' $patternVarDefinition)
     */
    _local_val_definition: $ => prec(
                                  1,
                                  seq(
                                    optional($._annotations),
                                    optional(alias('implicit', $.implicit_modifier)),
                                    optional(alias('lazy', $.lazy_modifier)),
                                    'val',
                                    field('pattern', $._pattern),
                                    optional(seq(':', field('type', $._type))),
                                    '=',
                                    field('value', $._expression)
                                  )
                                ),
    /*
     * scala.ebnf:152
     * _local_var_definition        ::= 1($localDefPrefix 'var' $patternVarDefinition)
     */
    _local_var_definition: $ => prec(
                                  1,
                                  seq(
                                    optional($._annotations),
                                    optional(alias('implicit', $.implicit_modifier)),
                                    optional(alias('lazy', $.lazy_modifier)),
                                    'var',
                                    field('pattern', $._pattern),
                                    optional(seq(':', field('type', $._type))),
                                    '=',
                                    field('value', $._expression)
                                  )
                                ),
    /*
     * scala.ebnf:153
     * _local_function_definition   ::= 1($localDefPrefix 'def' $functionDef)
     */
    _local_function_definition: $ => prec(
                                       1,
                                       seq(
                                         optional($._annotations),
                                         optional(alias('implicit', $.implicit_modifier)),
                                         optional(alias('lazy', $.lazy_modifier)),
                                         'def',
                                         field('name', $.identifier),
                                         field('type_parameters', optional($.type_parameters)),
                                         field('parameters', repeat($.parameters)),
                                         optional(seq(':', field('return_type', $._type))),
                                         choice(seq('=', field('body', $._expression)), field('body', $.block))
                                       )
                                     ),
    /*
     * scala.ebnf:154
     * _local_type_definition       ::= 1($localDefPrefix 'type' _newline* $typeDef)
     */
    _local_type_definition: $ => prec(
                                   1,
                                   seq(
                                     optional($._annotations),
                                     optional(alias('implicit', $.implicit_modifier)),
                                     optional(alias('lazy', $.lazy_modifier)),
                                     'type',
                                     repeat($._newline),
                                     field('name', $._type_identifier),
                                     field('type_parameters', optional($.type_parameters)),
                                     '=',
                                     field('type', $._type)
                                   )
                                 ),
    /*
     * scala.ebnf:156
     * val_definition               ::= _annotations? modifiers? 'val' $patternVarDefinition
     */
    val_definition: $ => seq(
                           optional($._annotations),
                           optional($.modifiers),
                           'val',
                           field('pattern', $._pattern),
                           optional(seq(':', field('type', $._type))),
                           '=',
                           field('value', $._expression)
                         ),
    /*
     * scala.ebnf:157
     * val_declaration              ::= _annotations? modifiers? 'val' $valDcl
     */
    val_declaration: $ => seq(
                            optional($._annotations),
                            optional($.modifiers),
                            'val',
                            seq(field('name', $.identifier), repeat(seq(',', field('name', $.identifier)))),
                            ':',
                            field('type', $._type)
                          ),
    /*
     * scala.ebnf:158
     * var_definition               ::= _annotations? modifiers? 'var' $patternVarDefinition
     */
    var_definition: $ => seq(
                           optional($._annotations),
                           optional($.modifiers),
                           'var',
                           field('pattern', $._pattern),
                           optional(seq(':', field('type', $._type))),
                           '=',
                           field('value', $._expression)
                         ),
    /*
     * scala.ebnf:159
     * var_declaration              ::= _annotations? modifiers? 'var' $varDcl
     */
    var_declaration: $ => seq(
                            optional($._annotations),
                            optional($.modifiers),
                            'var',
                            seq(field('name', $.identifier), repeat(seq(',', field('name', $.identifier)))),
                            ':',
                            field('type', $._type)
                          ),
    /*
     * scala.ebnf:160
     * type_definition              ::= _annotations? modifiers? 'type' _newline* $typeDef
     */
    type_definition: $ => seq(
                            optional($._annotations),
                            optional($.modifiers),
                            'type',
                            repeat($._newline),
                            field('name', $._type_identifier),
                            field('type_parameters', optional($.type_parameters)),
                            '=',
                            field('type', $._type)
                          ),
    /*
     * scala.ebnf:161
     * type_declaration             ::= _annotations? modifiers? 'type' _newline* $typeDcl
     */
    type_declaration: $ => seq(
                             optional($._annotations),
                             optional($.modifiers),
                             'type',
                             repeat($._newline),
                             field('name', $._type_parameter),
                             field('type_parameters', optional($.type_parameters)),
                             optional($.lower_bound),
                             optional($.upper_bound)
                           ),
    /*
     * scala.ebnf:162
     * function_definition          ::= _annotations? modifiers? 'def' $functionDef
     */
    function_definition: $ => seq(
                                optional($._annotations),
                                optional($.modifiers),
                                'def',
                                field('name', $.identifier),
                                field('type_parameters', optional($.type_parameters)),
                                field('parameters', repeat($.parameters)),
                                optional(seq(':', field('return_type', $._type))),
                                choice(seq('=', field('body', $._expression)), field('body', $.block))
                              ),
    /*
     * scala.ebnf:163
     * function_declaration         ::= _annotations? modifiers? 'def' $functionDcl
     */
    function_declaration: $ => seq(
                                 optional($._annotations),
                                 optional($.modifiers),
                                 'def',
                                 field('name', $.identifier),
                                 field('type_parameters', optional($.type_parameters)),
                                 field('parameters', repeat($.parameters)),
                                 optional(seq(':', field('return_type', $._type)))
                               ),
    /*
     * scala.ebnf:164
     * local_modifier               ::= 2('abstract' | 'final' | 'sealed' | 'implicit' | 'lazy')
     */
    local_modifier: $ => prec(2, choice('abstract', 'final', 'sealed', 'implicit', 'lazy')),
    /*
     * scala.ebnf:165
     * access_modifier              ::= ('private' | 'protected') access_qualifier?
     */
    access_modifier: $ => seq(choice('private', 'protected'), optional($.access_qualifier)),
    /*
     * scala.ebnf:166
     * access_qualifier             ::= '[' (identifier | 'this') ']'
     */
    access_qualifier: $ => seq('[', choice($.identifier, 'this'), ']'),
    /*
     * scala.ebnf:167
     * modifiers                    ::= (local_modifier | access_modifier | 'override')+
     */
    modifiers: $ => repeat1(choice($.local_modifier, $.access_modifier, 'override')),
    /*
     * scala.ebnf:196
     * _path                        ::= (_stable_identifier | (identifier '.')? 'this')
     */
    _path: $ => choice($._stable_identifier, seq(optional(seq($.identifier, '.')), 'this')),
    /*
     * scala.ebnf:201
     * stable_identifier            ::= 1(_stable_identifier)
     */
    stable_identifier: $ => prec(1, $._stable_identifier),
    /*
     * scala.ebnf:202-204
     * _stable_identifier           ::= 1(identifier
     *                                | path '.' identifier
     *                                | (identifier '.')?  'super' _class_qualifier?  '.' identifier)
     */
    _stable_identifier: $ => prec(
                               1,
                               choice(
                                 $.identifier,
                                 seq($._path, '.', $.identifier),
                                 seq(
                                   optional(seq($.identifier, '.')),
                                   'super',
                                   optional($._class_qualifier),
                                   '.',
                                   $.identifier
                                 )
                               )
                             ),
    /*
     * scala.ebnf:207
     * _class_qualifier             ::= "[" identifier "]"
     */
    _class_qualifier: $ => seq("[", $.identifier, "]"),
    /*
     * scala.ebnf:214
     * _type                        ::= 2(function_arg_types '=>' _type | _infix_type)
     */
    _type: $ => prec(2, choice(seq($.function_arg_types, '=>', $._type), $._infix_type)),
    /*
     * scala.ebnf:222
     * function_arg_types           ::= 1('(' (_type (',' _type)*)?  ')') | _infix_type
     */
    function_arg_types: $ => choice(
                               prec(1, seq('(', optional(seq($._type, repeat(seq(',', $._type)))), ')')),
                               $._infix_type
                             ),
    /*
     * scala.ebnf:227
     * _param_type                  ::= _type | '=>' _type |  _type '*'
     */
    _param_type: $ => choice($._type, seq('=>', $._type), seq($._type, '*')),
    /*
     * scala.ebnf:302
     * lazy_parameter_type          ::= '=>' (_type: type)
     */
    lazy_parameter_type: $ => seq('=>', field('type', $._type)),
    /*
     * scala.ebnf:303
     * repeated_parameter_type      ::= (_type: type) '*'
     */
    repeated_parameter_type: $ => seq(field('type', $._type), '*'),
    /*
     * scala.ebnf:231
     * _existential_clause          ::= 'forSome' '{' _existential_dcl (_semicolon _existential_dcl)* '}'
     */
    _existential_clause: $ => seq(
                                'forSome',
                                '{',
                                $._existential_dcl,
                                repeat(seq($._semicolon, $._existential_dcl)),
                                '}'
                              ),
    /*
     * scala.ebnf:235-237
     * _existential_dcl             ::= 'type' $typeDcl
     *                                | 'val' $valDcl
     * ;InfixType         ::=  CompoundType (id nl? CompoundType)*
     */
    _existential_dcl: $ => choice(
                             seq(
                               'type',
                               field('name', $._type_parameter),
                               field('type_parameters', optional($.type_parameters)),
                               optional($.lower_bound),
                               optional($.upper_bound)
                             ),
                             seq(
                               'val',
                               seq(field('name', $.identifier), repeat(seq(',', field('name', $.identifier)))),
                               ':',
                               field('type', $._type)
                             )
                           ),
    /*
     * scala.ebnf:238-240
     * _infix_type                  ::= <(_compound_type (identifier _newline? _compound_type)*)
     * ;CompoundType      ::=  AnnotType ('with' AnnotType)* Refinement?
     *                     ;|  Refinement
     */
    _infix_type: $ => prec.left(
                        seq(
                          $._compound_type,
                          repeat(seq($.identifier, optional($._newline), $._compound_type))
                        )
                      ),
    /*
     * scala.ebnf:241-242
     * _compound_type               ::= <(_annotated_type ('with' _annotated_type)* _refinement?
     *                                | _refinement)
     */
    _compound_type: $ => prec.left(
                           choice(
                             seq(
                               $._annotated_type,
                               repeat(seq('with', $._annotated_type)),
                               optional($._refinement)
                             ),
                             $._refinement
                           )
                         ),
    /*
     * scala.ebnf:243-250
     * _refinement                  ::= _block_newlines? '{' _refinement_statement (_semicolon _refinement_statement)* '}'
     * ;Dcl               ::=  ‘val’ ValDcl
     *                     ;|  ‘var’ VarDcl
     *                     ;|  ‘def’ FunDcl
     *                     ;|  ‘type’ {nl} TypeDcl
     * ;RefineStat        ::=  Dcl
     *                     ;|  'type' TypeDef
     *                     ;|
     */
    _refinement: $ => seq(
                        optional($._block_newlines),
                        '{',
                        $._refinement_statement,
                        repeat(seq($._semicolon, $._refinement_statement)),
                        '}'
                      ),
    /*
     * scala.ebnf:251-256
     * _refinement_statement        ::= 'val' $valDcl
     *                                | 'var' $varDcl
     *                                | 'def' $functionDcl
     *                                | 'type' _newline* $typeDcl
     *                                | 'type' $typeDef
     *                                | _empty
     */
    _refinement_statement: $ => choice(
                                  seq(
                                    'val',
                                    seq(field('name', $.identifier), repeat(seq(',', field('name', $.identifier)))),
                                    ':',
                                    field('type', $._type)
                                  ),
                                  seq(
                                    'var',
                                    seq(field('name', $.identifier), repeat(seq(',', field('name', $.identifier)))),
                                    ':',
                                    field('type', $._type)
                                  ),
                                  seq(
                                    'def',
                                    field('name', $.identifier),
                                    field('type_parameters', optional($.type_parameters)),
                                    field('parameters', repeat($.parameters)),
                                    optional(seq(':', field('return_type', $._type)))
                                  ),
                                  seq(
                                    'type',
                                    repeat($._newline),
                                    field('name', $._type_parameter),
                                    field('type_parameters', optional($.type_parameters)),
                                    optional($.lower_bound),
                                    optional($.upper_bound)
                                  ),
                                  seq(
                                    'type',
                                    field('name', $._type_identifier),
                                    field('type_parameters', optional($.type_parameters)),
                                    '=',
                                    field('type', $._type)
                                  ),
                                  $._empty
                                ),
    /*
     * scala.ebnf:257
     * singleton_type               ::= _path '.' 'type'
     */
    singleton_type: $ => seq($._path, '.', 'type'),
    /*
     * scala.ebnf:258
     * type_projection              ::= _simple_type '#' identifier
     */
    type_projection: $ => seq($._simple_type, '#', $.identifier),
    /*
     * scala.ebnf:259
     * tuple_types                  ::= '(' $types ')'
     */
    tuple_types: $ => seq('(', $._type, repeat(seq(',', $._type)), ')'),
    /*
     * scala.ebnf:262-266
     * _simple_type                 ::= $stableTypeIdentifer
     *                                | singleton_type
     *                                | type_projection
     *                                | tuple_types
     * ;AnnotType         ::=  SimpleType Annotation*
     */
    _simple_type: $ => choice(
                         $._type_identifier,
                         alias($.stable_identifier, $.stable_type_identifier),
                         $.singleton_type,
                         $.type_projection,
                         $.tuple_types
                       ),
    /*
     * scala.ebnf:267-268
     * _annotated_type              ::= 1(_simple_type annotation*)
     * ;TypeParamClause   ::=  '[' VariantTypeParam (',' VariantTypeParam)* ']'
     */
    _annotated_type: $ => prec(1, seq($._simple_type, repeat($.annotation))),
    /*
     * scala.ebnf:271
     * type_parameters              ::= '[' (_variant_type_parameter (',' _variant_type_parameter)*) ']'
     */
    type_parameters: $ => seq(
                            '[',
                            seq($._variant_type_parameter, repeat(seq(',', $._variant_type_parameter))),
                            ']'
                          ),
    /*
     * scala.ebnf:272
     * _variant_type_parameter      ::= _annotations? (covariant_type_parameter | contravariant_type_parameter | _type_parameter)
     */
    _variant_type_parameter: $ => seq(
                                    optional($._annotations),
                                    choice($.covariant_type_parameter, $.contravariant_type_parameter, $._type_parameter)
                                  ),
    /*
     * scala.ebnf:273
     * covariant_type_parameter     ::= '+' _type_parameter
     */
    covariant_type_parameter: $ => seq('+', $._type_parameter),
    /*
     * scala.ebnf:274
     * contravariant_type_parameter ::= '-' _type_parameter
     */
    contravariant_type_parameter: $ => seq('-', $._type_parameter),
    /*
     * scala.ebnf:275-276
     * _type_parameter              ::= 1>(((wildcard | identifier): name) (type_parameters?: type_parameters)
     *                                    (upper_bound?: bound) (lower_bound?: bound) (view_bound*?: bound) (context_bound*?: bound))
     */
    _type_parameter: $ => prec.right(
                            1,
                            seq(
                              field('name', choice($.wildcard, $.identifier)),
                              field('type_parameters', optional($.type_parameters)),
                              field('bound', optional($.upper_bound)),
                              field('bound', optional($.lower_bound)),
                              field('bound', optional(repeat($.view_bound))),
                              field('bound', optional(repeat($.context_bound)))
                            )
                          ),
    /*
     * scala.ebnf:277
     * upper_bound                  ::= '<:' (_type: type)
     */
    upper_bound: $ => seq('<:', field('type', $._type)),
    /*
     * scala.ebnf:278
     * lower_bound                  ::= '>:' (_type: type)
     */
    lower_bound: $ => seq('>:', field('type', $._type)),
    /*
     * scala.ebnf:279
     * view_bound                   ::= '<%' (_type: type)
     */
    view_bound: $ => seq('<%', field('type', $._type)),
    /*
     * scala.ebnf:280-281
     * context_bound                ::= ':' (_type: type)
     * ; template_body                ::= '{' _block? '}'
     */
    context_bound: $ => seq(':', field('type', $._type)),
    /*
     * scala.ebnf:282
     * extends_clause               ::= 'extends' (_type: type) arguments?
     */
    extends_clause: $ => seq('extends', field('type', $._type), optional($.arguments)),
    /*
     * scala.ebnf:283
     * class_parameters             ::= '(' 'implicit'? (class_parameter (',' class_parameter)*)? ')'
     */
    class_parameters: $ => seq(
                             '(',
                             optional('implicit'),
                             optional(seq($.class_parameter, repeat(seq(',', $.class_parameter)))),
                             ')'
                           ),
    /*
     * scala.ebnf:284
     * parameters                   ::= '(' 'implicit'? (parameter (',' parameter)*)? ')'
     */
    parameters: $ => seq(
                       '(',
                       optional('implicit'),
                       optional(seq($.parameter, repeat(seq(',', $.parameter)))),
                       ')'
                     ),
    /*
     * scala.ebnf:285-286
     * class_parameter              ::= annotation* ('val' | 'var')? (identifier: name) (':' (_type: type))?
     *                                    ('=' (_expression: default_value))?
     */
    class_parameter: $ => seq(
                            repeat($.annotation),
                            optional(choice('val', 'var')),
                            field('name', $.identifier),
                            optional(seq(':', field('type', $._type))),
                            optional(seq('=', field('default_value', $._expression)))
                          ),
    /*
     * scala.ebnf:287
     * parameter                    ::= annotation* (identifier: name) (':' (_param_type: type))? ('=' (_expression: default_value))?
     */
    parameter: $ => seq(
                      repeat($.annotation),
                      field('name', $.identifier),
                      optional(seq(':', field('type', $._param_type))),
                      optional(seq('=', field('default_value', $._expression)))
                    ),
    /*
     * scala.ebnf:288
     * _block                       ::= <(((_expression | _definition) (_semicolon (_expression | _definition))*) _semicolon?)
     */
    _block: $ => prec.left(
                   seq(
                     seq(
                       choice($._expression, $._definition),
                       repeat(seq($._semicolon, choice($._expression, $._definition)))
                     ),
                     optional($._semicolon)
                   )
                 ),
    /*
     * scala.ebnf:289
     * block                        ::= '{' _block? '}'
     */
    block: $ => seq('{', optional($._block), '}'),
    /*
     * scala.ebnf:293
     * compound_type                ::= 3((_annotated_type: base) ('with' (_annotated_type: extra))+)
     */
    compound_type: $ => prec(
                          3,
                          seq(
                            field('base', $._annotated_type),
                            repeat1(seq('with', field('extra', $._annotated_type)))
                          )
                        ),
    /*
     * scala.ebnf:294-296
     * infix_type                   ::= <2(((compound_type | infix_type | _annotated_type): left)
     *                                    ((identifier): operator)
     *                                    ((compound_type | infix_type | _annotated_type): right))
     */
    infix_type: $ => prec.left(
                       2,
                       seq(
                         field('left', choice($.compound_type, $.infix_type, $._annotated_type)),
                         field('operator', $.identifier),
                         field('right', choice($.compound_type, $.infix_type, $._annotated_type))
                       )
                     ),
    /*
     * scala.ebnf:298-301
     * parameter_types              ::= -1(_annotated_type
     *                                | ~1('(' (_param_type (',' _param_type)*)? ')')
     *                                | compound_type
     *                                | infix_type)
     */
    parameter_types: $ => prec(
                            -1,
                            choice(
                              $._annotated_type,
                              prec.dynamic(1, seq('(', optional(seq($._param_type, repeat(seq(',', $._param_type)))), ')')),
                              $.compound_type,
                              $.infix_type
                            )
                          ),
    /*
     * scala.ebnf:302
     * lazy_parameter_type          ::= '=>' (_type: type)
     */
    lazy_parameter_type: $ => seq('=>', field('type', $._type)),
    /*
     * scala.ebnf:303
     * repeated_parameter_type      ::= (_type: type) '*'
     */
    repeated_parameter_type: $ => seq(field('type', $._type), '*'),
    /*
     * scala.ebnf:304
     * _type_identifier             ::= identifier -> type_identifier
     */
    _type_identifier: $ => alias($.identifier, $.type_identifier),
    /*
     * scala.ebnf:305-317
     * _pattern                     ::= identifier
     *                                | capture_pattern
     *                                | tuple_pattern
     *                                | case_class_pattern
     *                                | infix_pattern
     *                                | alternative_pattern
     *                                | typed_pattern
     *                                | number
     *                                | boolean_literal
     *                                | character_literal
     *                                | symbol_literal
     *                                | string_literal
     *                                | wildcard
     */
    _pattern: $ => choice(
                     $.identifier,
                     $.capture_pattern,
                     $.tuple_pattern,
                     $.case_class_pattern,
                     $.infix_pattern,
                     $.alternative_pattern,
                     $.typed_pattern,
                     $.number,
                     $.boolean_literal,
                     $.character_literal,
                     $.symbol_literal,
                     $.string_literal,
                     $.wildcard
                   ),
    /*
     * scala.ebnf:318
     * case_class_pattern           ::= ($stableTypeIdentifer: type) '(' ((_pattern (',' _pattern)*)?: pattern) ')'
     */
    case_class_pattern: $ => seq(
                               field(
                                 'type',
                                 choice($._type_identifier, alias($.stable_identifier, $.stable_type_identifier))
                               ),
                               '(',
                               field('pattern', optional(seq($._pattern, repeat(seq(',', $._pattern))))),
                               ')'
                             ),
    /*
     * scala.ebnf:319
     * infix_pattern                ::= <2((_pattern: left) ((identifier): operator) (_pattern: right))
     */
    infix_pattern: $ => prec.left(
                          2,
                          seq(
                            field('left', $._pattern),
                            field('operator', $.identifier),
                            field('right', $._pattern)
                          )
                        ),
    /*
     * scala.ebnf:320
     * capture_pattern              ::= 1((identifier: name) '@' (_pattern: pattern))
     */
    capture_pattern: $ => prec(1, seq(field('name', $.identifier), '@', field('pattern', $._pattern))),
    /*
     * scala.ebnf:321
     * typed_pattern                ::= -1((_pattern: pattern) ':' (_type: type))
     */
    typed_pattern: $ => prec(-1, seq(field('pattern', $._pattern), ':', field('type', $._type))),
    /*
     * scala.ebnf:322
     * alternative_pattern          ::= <-2(_pattern '|' _pattern)
     */
    alternative_pattern: $ => prec.left(-2, seq($._pattern, '|', $._pattern)),
    /*
     * scala.ebnf:323
     * tuple_pattern                ::= '(' _pattern (',' _pattern)+ ')'
     */
    tuple_pattern: $ => seq('(', $._pattern, repeat1(seq(',', $._pattern)), ')'),
    /*
     * scala.ebnf:324-333
     * _expression                  ::= if_expression
     *                                | match_expression
     *                                | try_expression
     *                                | for_expression
     *                                | while_expression
     *                                | do_expression
     *                                | call_expression
     *                                | assignment_expression
     *                                | infix_expression
     *                                | _simple_expression
     */
    _expression: $ => choice(
                        $.if_expression,
                        $.match_expression,
                        $.try_expression,
                        $.for_expression,
                        $.while_expression,
                        $.do_expression,
                        $.call_expression,
                        $.assignment_expression,
                        $.infix_expression,
                        $._simple_expression
                      ),
    /*
     * scala.ebnf:334-341
     * _simple_expression           ::= parenthesized_expression
     *                                | instance_expression
     *                                | prefix_expression
     *                                | tuple_expression
     *                                | case_block
     *                                | block
     *                                | identifier
     *                                | literal
     */
    _simple_expression: $ => choice(
                               $.parenthesized_expression,
                               $.instance_expression,
                               $.prefix_expression,
                               $.tuple_expression,
                               $.case_block,
                               $.block,
                               $.identifier,
                               $._literal
                             ),
    /*
     * scala.ebnf:342-343
     * if_expression                ::= >('if' (parenthesized_expression: condition) (_expression: consequence)
     *                                    ('else' (_expression: alternative))?)
     */
    if_expression: $ => prec.right(
                          seq(
                            'if',
                            field('condition', $.parenthesized_expression),
                            field('consequence', $._expression),
                            optional(seq('else', field('alternative', $._expression)))
                          )
                        ),
    /*
     * scala.ebnf:344
     * match_expression             ::= 1(_expression: value) 'match' (case_block: body)
     */
    match_expression: $ => seq(prec(1, field('value', $._expression)), 'match', field('body', $.case_block)),
    /*
     * scala.ebnf:345
     * try_expression               ::= >('try' (_expression: body) catch_clause? finally_clause?)
     */
    try_expression: $ => prec.right(
                           seq(
                             'try',
                             field('body', $._expression),
                             optional($.catch_clause),
                             optional($.finally_clause)
                           )
                         ),
    /*
     * scala.ebnf:346
     * catch_clause                 ::= >('catch' case_block)
     */
    catch_clause: $ => prec.right(seq('catch', $.case_block)),
    /*
     * scala.ebnf:347
     * finally_clause               ::= >('finally' _expression)
     */
    finally_clause: $ => prec.right(seq('finally', $._expression)),
    /*
     * scala.ebnf:348
     * case_block                   ::= -1('{' '}') | ('{' case_clause+ '}')
     */
    case_block: $ => choice(prec(-1, seq('{', '}')), seq('{', repeat1($.case_clause), '}')),
    /*
     * scala.ebnf:349
     * case_clause                  ::= <('case' (_pattern: pattern) guard? '=>' (_block?: body))
     */
    case_clause: $ => prec.left(
                        seq(
                          'case',
                          field('pattern', $._pattern),
                          optional($.guard),
                          '=>',
                          field('body', optional($._block))
                        )
                      ),
    /*
     * scala.ebnf:350
     * guard                        ::= 'if' (_expression: condition)
     */
    guard: $ => seq('if', field('condition', $._expression)),
    /*
     * scala.ebnf:352
     * enumerators                  ::= <(generator (_semicolon generator)*)
     */
    enumerators: $ => prec.left(seq($.generator, repeat(seq($._semicolon, $.generator)))),
    /*
     * scala.ebnf:353
     * generator                    ::= <(_pattern '<-' _expression (_semicolon? guard | _semicolon _pattern '=' _expression)*)
     */
    generator: $ => prec.left(
                      seq(
                        $._pattern,
                        '<-',
                        $._expression,
                        repeat(
                          choice(
                            seq(optional($._semicolon), $.guard),
                            seq($._semicolon, $._pattern, '=', $._expression)
                          )
                        )
                      )
                    ),
    /*
     * scala.ebnf:354
     * for_expression               ::= 3<('for' ('(' enumerators ')' | '{' enumerators _semicolon?  '}') _newline* 'yield'? _expression)
     */
    for_expression: $ => prec.left(
                           3,
                           seq(
                             'for',
                             choice(
                               seq('(', $.enumerators, ')'),
                               seq('{', $.enumerators, optional($._semicolon), '}')
                             ),
                             repeat($._newline),
                             optional('yield'),
                             $._expression
                           )
                         ),
    /*
     * scala.ebnf:356
     * while_expression             ::= 2('while' '(' _expression ')' _newline* _expression)
     */
    while_expression: $ => prec(2, seq('while', '(', $._expression, ')', repeat($._newline), $._expression)),
    /*
     * scala.ebnf:357
     * do_expression                ::= ('do' _expression _semicolon? 'while' '(' _expression ')')
     */
    do_expression: $ => seq('do', $._expression, optional($._semicolon), 'while', '(', $._expression, ')'),
    /*
     * scala.ebnf:359
     * assignment_expression        ::= >1((_expression: left) '=' (_expression: right))
     */
    assignment_expression: $ => prec.right(1, seq(field('left', $._expression), '=', field('right', $._expression))),
    /*
     * scala.ebnf:360
     * call_expression              ::= 4((_expression: function) (arguments: arguments) ((block | case_block)?: body))
     */
    call_expression: $ => prec(
                            4,
                            seq(
                              field('function', $._expression),
                              field('arguments', $.arguments),
                              field('body', optional(choice($.block, $.case_block)))
                            )
                          ),
    /*
     * scala.ebnf:361
     * field_expression             ::= 4((_expression: value) '.' (identifier: field))
     */
    field_expression: $ => prec(4, seq(field('value', $._expression), '.', field('field', $.identifier))),
    /*
     * scala.ebnf:362
     * instance_expression          ::= 3('new' _expression)
     */
    instance_expression: $ => prec(3, seq('new', $._expression)),
    /*
     * scala.ebnf:363
     * infix_expression             ::= <2((_simple_expression: left) ((identifier): operator) (_expression: right))
     */
    infix_expression: $ => prec.left(
                             2,
                             seq(
                               field('left', $._simple_expression),
                               field('operator', $.identifier),
                               field('right', $._expression)
                             )
                           ),
    /*
     * scala.ebnf:364
     * prefix_expression            ::= 3(('+' | '-' | '!' | '~') _simple_expression)
     */
    prefix_expression: $ => prec(3, seq(choice('+', '-', '!', '~'), $._simple_expression)),
    /*
     * scala.ebnf:365
     * tuple_expression             ::= '(' _expression (',' _expression)+ ')'
     */
    tuple_expression: $ => seq('(', $._expression, repeat1(seq(',', $._expression)), ')'),
    /*
     * scala.ebnf:366
     * parenthesized_expression     ::= '(' _expression ')'
     */
    parenthesized_expression: $ => seq('(', $._expression, ')'),
    /*
     * scala.ebnf:367
     * arguments                    ::= '(' (_expression (',' _expression)*)? ')'
     */
    arguments: $ => seq('(', optional(seq($._expression, repeat(seq(',', $._expression)))), ')'),
    /*
     * scala.ebnf:388
     * identifier                   ::= /($opchar+|$idRegex|$varidRegex|[`]$varidRegex[`])/
     */
    identifier: $ => /([\-!#%&*+/\\:<=>?@\u005e\u007c~]+|([\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$][\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]*(_[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)?|[\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F_][\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]*(_[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)?|[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)|[`]([\u0020-\u005f\u0061-\u007f]|(\\u+[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]|\\[btnfr"'\\]))*[`]|[\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F_][\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]*(_[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)?|[`][\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F_][\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]*(_[\-!#%&*+/\\:<=>?@\u005e\u007c~]+)?[`])/,
    /*
     * scala.ebnf:389
     * wildcard                     ::= '_'
     */
    wildcard: $ => '_',
    /*
     * scala.ebnf:401
     * number                       ::= $integer_literal | $floating_point_literal
     */
    number: $ => choice(
                   /-?([0-9]+|0[xX][0-9a-fA-F]+)[Ll]?/,
                   /-?([0-9]+[.][0-9]+([Ee][+-]?[0-9]+)?[FfDd]?|[.][0-9]+([Ee][+-]?[0-9]+)?[FfDd]?|[0-9]+([Ee][+-]?[0-9]+)?[FfDd]|[0-9]+([Ee][+-]?[0-9]+)[FfDd]?)/
                 ),
    /*
     * scala.ebnf:402
     * boolean_literal              ::= 'true' | 'false'
     */
    boolean_literal: $ => choice('true', 'false'),
    /*
     * scala.ebnf:403
     * character_literal            ::= /'([\u0020-\u0026\u0028-\u007f]|\\[btnfr"'\\]|\\u+[0-9a-fA-F]{4})'/
     */
    character_literal: $ => /'([\u0020-\u0026\u0028-\u007f]|\\[btnfr"'\\]|\\u+[0-9a-fA-F]{4})'/,
    /*
     * scala.ebnf:404
     * symbol_literal               ::= @("'" [^\\'\n]+)
     */
    symbol_literal: $ => token(seq("'", repeat1(/[^\\'\n]/))),
    /*
     * scala.ebnf:406
     * _interpolation_string_prefix ::= !(($upper $idrest): interpolation_name '"') | !($varidRegex: interpolation_name '"')
     */
    _interpolation_string_prefix: $ => choice(
                                         token.immediate(
                                           seq(
                                             field(
                                               'interpolation_name',
                                               seq(
                                                 /[\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$]/,
                                                 repeat(
                                                   /[\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]/
                                                 ),
                                                 optional(repeat1(/[\-!#%&*+/\\:<=>?@\u005e\u007c~]/))
                                               )
                                             ),
                                             '"'
                                           )
                                         ),
                                         token.immediate(
                                           seq(
                                             /[\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F_]/,
                                             repeat(
                                               /[\p{Lu}\p{Lt}\p{Nl}\p{Lo}\p{Lm}\$\p{Ll}_\u00AA\u00BB\u02B0-\u02B8\u02C0-\u02C1\u02E0-\u02E4\u037A\u1D78\u1D9B-\u1DBF\u2071\u207F\u2090-\u209C\u2C7C-\u2C7D\uA69C-\uA69D\uA770\uA7F8-\uA7F9\uAB5C-\uAB5F0-9]/
                                             ),
                                             field('interpolation_name', optional(repeat1(/[\-!#%&*+/\\:<=>?@\u005e\u007c~]/))),
                                             '"'
                                           )
                                         )
                                       ),
    /*
     * scala.ebnf:408-409
     * interpolated_string          ::= _interpolation_string_prefix ($charMinusQuoteDollar | _escape)* '"'
     *                                | _interpolation_string_prefix '""' ('"'? '"'? $charMinusQuoteDollar | _escape)* '"'? '"""'
     */
    interpolated_string: $ => choice(
                                seq($._interpolation_string_prefix, repeat(choice(/[^"\$]/, $._escape)), '"'),
                                seq(
                                  $._interpolation_string_prefix,
                                  '""',
                                  repeat(choice(seq(optional('"'), optional('"'), /[^"\$]/), $._escape)),
                                  optional('"'),
                                  '"""'
                                )
                              ),
    /*
     * scala.ebnf:410
     * _escape                      ::= "$$" | "$" identifier | "$" block
     */
    _escape: $ => choice("$$", seq("$", $.identifier), seq("$", $.block)),
    /*
     * scala.ebnf:411
     * _raw_string                  ::= /"""("?"?[^"])*"*"""/
     */
    _raw_string: $ => /"""("?"?[^"])*"*"""/,
    /*
     * scala.ebnf:412
     * _simple_string               ::= !('"' /[^"\n]|$escapeSeq/* '"') | '""'
     */
    _simple_string: $ => choice(
                           token.immediate(
                             seq(
                               '"',
                               repeat(
                                 /[^"\n]|(\\u+[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]|\\[btnfr"'\\])/
                               ),
                               '"'
                             )
                           ),
                           '""'
                         ),
    /*
     * scala.ebnf:416
     * string_literal               ::= _simple_string | _raw_string
     */
    string_literal: $ => choice($._simple_string, $._raw_string),
    /*
     * scala.ebnf:417
     * _semicolon                   ::= ';' | _automatic_semicolon
     */
    _semicolon: $ => choice(';', $._automatic_semicolon)
  }
});
